export const SET_GEARS_CONFIG = 'SET_GEARS_CONFIG';
export const CHANGE_THREAD_TYPE = 'CHANGE_THREAD_TYPE';
export const TOGGLE_APPROX = 'TOGGLE_APPROX';
export const TOGGLE_UNIQUE_GEARS = 'TOGGLE_UNIQUE_GEARS';
export const SELECT_GEAR = 'SELECT_GEAR';
